services:
  - type: web
    name: pixel-logic-website
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: public
    envVars:
      - key: NODE_VERSION
        value: "20"
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /page-data/*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
